/**
 * punk-records importer — the One Piece card corpus (build plan §5/M4, P4.1).
 *
 * Upstream is buhbbl/punk-records: static JSON regenerated by automated
 * commits to main every 3–7 days (no releases/tags), so "versioned" means
 * WE pin: each run resolves main's HEAD sha via one GitHub API call and
 * compares it against the last succeeded run's stats (the topdeck.ts
 * last-succeeded-run pattern). Unchanged sha + unchanged mapper + unchanged
 * image base = clean no-op (recorded as a succeeded run so observability
 * shows the check happened). All content fetches go to
 * raw.githubusercontent.com AT THE PINNED SHA — ~62 small requests, 100ms
 * apart, real User-Agent; this is one volunteer's free repo, never hammer it.
 *
 * Sources within the sha (see punk-map.ts for the schema-drift story):
 *   english/packs.json                 → sets (60)
 *   english/data/<pack_id>.json  × 60  → card identities (base entries only)
 *   english/index/cards_by_id.json     → printings (base + _pN + _rN)
 *
 * Same staging + tuple-compare merge + soft-delete sweep as scryfall.ts;
 * no prices, no legality rows (the optcg standard format row's
 * defaultLegality='legal' carries the whole load until M4's real banlist).
 *
 * Run: pnpm ingest:punk-records
 * Env: PUNK_RECORDS_SHA (pin/rollback override), PUNK_FORCE=1 (re-ingest an
 * unchanged sha, e.g. after a mapper fix), R2_PUBLIC_IMAGE_BASE (serve card
 * images from the R2 mirror instead of hotlinking Bandai — an owner flip).
 */
import { config as loadEnv } from "dotenv";

loadEnv({ path: [".env.local", ".env"], quiet: true });

import postgres from "postgres";

import { GAME_ID } from "../../src/db/seed-data";
import {
  baseCardId,
  mapOptcgIdentity,
  mapOptcgPrinting,
  packSetCode,
  packSetName,
  type OptcgIdentityRow,
  type OptcgPrintingRow,
  type PunkCard,
  type PunkIndexEntry,
  type PunkPack,
} from "../../src/lib/games/optcg/punk-map";
import { applyOptcgLegalities, type OverlayApplyStats } from "./optcg-legalities";

const USER_AGENT = "Deckwarden/1.0 (https://deckwarden.gg)";
const HEADERS = { "User-Agent": USER_AGENT, Accept: "application/json" };
const REPO = "buhbbl/punk-records";
const RAW_BASE = `https://raw.githubusercontent.com/${REPO}`;
/** Bump when punk-map.ts mapping changes — forces a re-ingest at an unchanged sha. */
const MAPPER_VERSION = 1;
const FETCH_DELAY_MS = 100;
const BATCH_SIZE = 1000;
/** Session-wide lock id shared by all Deckwarden ingest jobs. */
const INGEST_LOCK_KEY = 7234015309;

function directUrl(): string {
  const url = process.env.DATABASE_URL_UNPOOLED ?? process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is not set (see .env.example)");
  return url.replace("-pooler.", ".");
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url, { headers: HEADERS });
  if (!res.ok) throw new Error(`GET ${url} → ${res.status}`);
  return (await res.json()) as T;
}

async function latestSha(): Promise<string> {
  const commits = await fetchJson<Array<{ sha: string }>>(
    `https://api.github.com/repos/${REPO}/commits?per_page=1`,
  );
  if (!commits[0]?.sha) throw new Error("could not resolve punk-records HEAD sha");
  return commits[0].sha;
}

interface Stats {
  sha: string;
  mapper_version: number;
  image_base: string | null;
  skipped_unchanged?: boolean;
  legalities_overlay?: OverlayApplyStats;
  requests: number;
  packs: number;
  sets_upserted: number;
  identities: { staged: number; inserted: number; updated: number };
  printings: { staged: number; inserted: number; updated: number };
  reconcile: {
    base_ids_expected: number;
    base_ids_staged: number;
    index_entries: number;
    leaders: number;
    variants_without_base: number;
    base_without_data_entry: number;
  };
  post_pass: { identities_removed: number; printings_removed: number };
  duration_ms: number;
  db_size_bytes: number;
}

async function main() {
  const started = Date.now();
  const imageBase = process.env.R2_PUBLIC_IMAGE_BASE?.trim() || null;
  const sql = postgres(directUrl(), { max: 1, prepare: false, idle_timeout: 0 });
  let runId: number | undefined;

  try {
    const [{ locked }] = await sql<
      { locked: boolean }[]
    >`SELECT pg_try_advisory_lock(${INGEST_LOCK_KEY}) AS locked`;
    if (!locked) {
      console.error("another ingest holds the advisory lock; exiting");
      process.exit(2);
    }

    // Banlist overlay applier (P4.2) — UNCONDITIONALLY, before the sha-skip
    // exit: data/optcg/legalities.json changes with Bandai announcements, not
    // upstream commits, so overlay edits must land within a nightly either way.
    const overlayStats = await applyOptcgLegalities(sql);

    const sha = process.env.PUNK_RECORDS_SHA?.trim() || (await latestSha());
    console.log(`punk-records pinned sha: ${sha}`);

    // Unchanged upstream + unchanged mapping + unchanged image base → no-op.
    const [last] = await sql<{ stats: Record<string, unknown> | null }[]>`
      SELECT stats FROM ingest_runs
      WHERE source = 'punk-records' AND status = 'succeeded'
      ORDER BY started_at DESC LIMIT 1`;
    const unchanged =
      last?.stats?.sha === sha &&
      last?.stats?.mapper_version === MAPPER_VERSION &&
      (last?.stats?.image_base ?? null) === imageBase;
    if (unchanged && process.env.PUNK_FORCE !== "1") {
      await sql`INSERT INTO ingest_runs (source, status, finished_at, stats)
        VALUES ('punk-records', 'succeeded', now(),
                ${sql.json({ sha, mapper_version: MAPPER_VERSION, image_base: imageBase, skipped_unchanged: true, legalities_overlay: { ...overlayStats }, duration_ms: Date.now() - started })})`;
      console.log("sha, mapper and image base unchanged since last success — clean no-op skip");
      return;
    }

    const [run] = await sql<{ id: number }[]>`
      INSERT INTO ingest_runs (source, status) VALUES ('punk-records', 'running') RETURNING id`;
    runId = run.id;

    const stats: Stats = {
      sha,
      mapper_version: MAPPER_VERSION,
      image_base: imageBase,
      legalities_overlay: overlayStats,
      requests: 0,
      packs: 0,
      sets_upserted: 0,
      identities: { staged: 0, inserted: 0, updated: 0 },
      printings: { staged: 0, inserted: 0, updated: 0 },
      reconcile: {
        base_ids_expected: 0,
        base_ids_staged: 0,
        index_entries: 0,
        leaders: 0,
        variants_without_base: 0,
        base_without_data_entry: 0,
      },
      post_pass: { identities_removed: 0, printings_removed: 0 },
      duration_ms: 0,
      db_size_bytes: 0,
    };
    const raw = async <T>(path: string): Promise<T> => {
      await sleep(FETCH_DELAY_MS);
      stats.requests++;
      return fetchJson<T>(`${RAW_BASE}/${sha}/${path}`);
    };

    // ---- Fetch (pinned sha, politely paced) --------------------------------
    const packs = await raw<Record<string, PunkPack>>("english/packs.json");
    const packIds = Object.keys(packs);
    stats.packs = packIds.length;
    console.log(`packs: ${packIds.length}`);

    const fullById = new Map<string, PunkCard>();
    for (const packId of packIds) {
      const cards = await raw<PunkCard[]>(`english/data/${packId}.json`);
      // Aggregates repeat reprints/parallels across packs; base entries only,
      // first occurrence wins (duplicate contents verified identical upstream).
      for (const card of cards) {
        if (card.id.includes("_")) continue;
        if (!fullById.has(card.id)) fullById.set(card.id, card);
      }
    }
    const index = await raw<Record<string, PunkIndexEntry>>("english/index/cards_by_id.json");
    const indexKeys = Object.keys(index);
    console.log(`base cards: ${fullById.size}, index entries: ${indexKeys.length}`);

    // ---- Reconcile against the corpus shape before touching the DB ---------
    const baseKeys = indexKeys.filter((k) => !k.includes("_"));
    stats.reconcile.base_ids_expected = baseKeys.length;
    stats.reconcile.index_entries = indexKeys.length;
    stats.reconcile.variants_without_base = indexKeys.filter(
      (k) => k.includes("_") && !index[baseCardId(k)],
    ).length;
    stats.reconcile.base_without_data_entry = baseKeys.filter((k) => !fullById.has(k)).length;
    if (stats.reconcile.variants_without_base > 0 || stats.reconcile.base_without_data_entry > 0) {
      // A variant with no base identity (or a base with no full record) means
      // the upstream layout drifted — refuse to half-ingest.
      throw new Error(
        `corpus reconciliation failed: ${JSON.stringify(stats.reconcile)} — upstream layout drift?`,
      );
    }

    // ---- Sets ---------------------------------------------------------------
    const setRows = packIds.flatMap((pid) => {
      const code = packSetCode(packs[pid]);
      if (!code) {
        console.warn(`pack ${pid} has no derivable set code — skipped`);
        return [];
      }
      return [
        {
          game_id: GAME_ID.optcg,
          code,
          name: packSetName(packs[pid]),
          released_at: null, // punk-records carries no release dates (punk-map.ts)
          set_type: null,
          digital: false,
        },
      ];
    });
    await sql`
      INSERT INTO sets ${sql(setRows)}
      ON CONFLICT ON CONSTRAINT sets_game_code DO UPDATE SET name = excluded.name`;
    const setIdRows = await sql<{ id: number; code: string }[]>`
      SELECT id, code FROM sets WHERE game_id = ${GAME_ID.optcg}`;
    const setIdByCode = new Map(setIdRows.map((r) => [r.code, r.id]));
    const setIdByPack = new Map(
      packIds.flatMap((pid) => {
        const code = packSetCode(packs[pid]);
        const id = code ? setIdByCode.get(code) : undefined;
        return id ? [[pid, id] as const] : [];
      }),
    );
    stats.sets_upserted = setRows.length;

    // ---- Stage --------------------------------------------------------------
    await sql`CREATE TEMP TABLE stage_ci (
      game_id smallint, external_key text, name text, name_norm text, primary_type text,
      cost_value smallint, colors_mask smallint, ci_mask smallint,
      is_leader_candidate boolean, popularity integer, is_preview boolean, attrs text)`;
    await sql`CREATE TEMP TABLE stage_cp (
      id uuid, external_key text, game_id smallint, set_id integer, collector_number text,
      rarity text, finishes text[], has_back boolean, is_default boolean,
      image_override text, content_hash text)`;

    let ciBatch: OptcgIdentityRow[] = [];
    for (const card of fullById.values()) {
      const row = mapOptcgIdentity(card);
      if (row.is_leader_candidate) stats.reconcile.leaders++;
      ciBatch.push(row);
      if (ciBatch.length >= BATCH_SIZE) {
        await sql`INSERT INTO stage_ci ${sql(ciBatch)}`;
        stats.identities.staged += ciBatch.length;
        ciBatch = [];
      }
    }
    if (ciBatch.length) {
      await sql`INSERT INTO stage_ci ${sql(ciBatch)}`;
      stats.identities.staged += ciBatch.length;
    }
    stats.reconcile.base_ids_staged = stats.identities.staged;

    let cpBatch: (Omit<OptcgPrintingRow, "pack_id"> & { set_id: number })[] = [];
    for (const key of indexKeys) {
      const { pack_id, ...mapped } = mapOptcgPrinting(key, index[key], imageBase);
      const setId = setIdByPack.get(pack_id);
      if (!setId) throw new Error(`printing ${key} references unknown pack ${pack_id}`);
      cpBatch.push({ ...mapped, set_id: setId });
      if (cpBatch.length >= BATCH_SIZE) {
        await sql`INSERT INTO stage_cp ${sql(cpBatch)}`;
        stats.printings.staged += cpBatch.length;
        cpBatch = [];
      }
    }
    if (cpBatch.length) {
      await sql`INSERT INTO stage_cp ${sql(cpBatch)}`;
      stats.printings.staged += cpBatch.length;
    }

    // ---- Merge (scryfall.ts pattern: update only on real change) -----------
    const ciRes = await sql<{ inserted: boolean }[]>`
      INSERT INTO card_identities AS ci
        (game_id, external_key, name, name_norm, primary_type, cost_value,
         colors_mask, ci_mask, is_leader_candidate, popularity, is_preview,
         is_removed, attrs, seen_at)
      SELECT s.game_id, s.external_key, s.name, s.name_norm, s.primary_type, s.cost_value,
             s.colors_mask, s.ci_mask, s.is_leader_candidate, s.popularity, s.is_preview,
             false, s.attrs::jsonb, now()
      FROM stage_ci s
      ON CONFLICT (game_id, external_key) DO UPDATE SET
        name = excluded.name, name_norm = excluded.name_norm,
        primary_type = excluded.primary_type, cost_value = excluded.cost_value,
        colors_mask = excluded.colors_mask, ci_mask = excluded.ci_mask,
        is_leader_candidate = excluded.is_leader_candidate,
        popularity = excluded.popularity, is_preview = excluded.is_preview,
        is_removed = false, attrs = excluded.attrs, seen_at = now()
      WHERE (ci.name, ci.name_norm, ci.primary_type, ci.cost_value, ci.colors_mask,
             ci.ci_mask, ci.is_leader_candidate, ci.popularity, ci.is_preview,
             ci.is_removed, ci.attrs)
        IS DISTINCT FROM
            (excluded.name, excluded.name_norm, excluded.primary_type, excluded.cost_value,
             excluded.colors_mask, excluded.ci_mask, excluded.is_leader_candidate,
             excluded.popularity, excluded.is_preview, false, excluded.attrs)
      RETURNING (xmax = 0) AS inserted`;
    stats.identities.inserted = ciRes.filter((r) => r.inserted).length;
    stats.identities.updated = ciRes.length - stats.identities.inserted;

    const cpRes = await sql<{ inserted: boolean }[]>`
      INSERT INTO card_printings AS cp
        (id, card_identity_id, game_id, set_id, collector_number, rarity, finishes,
         has_back, image_override, released_at, is_default, content_hash, is_removed, seen_at)
      SELECT s.id, ci.id, s.game_id, s.set_id, s.collector_number, s.rarity, s.finishes,
             s.has_back, s.image_override::jsonb, NULL, s.is_default, s.content_hash, false, now()
      FROM stage_cp s
      JOIN card_identities ci ON ci.game_id = s.game_id AND ci.external_key = s.external_key
      ON CONFLICT (id) DO UPDATE SET
        card_identity_id = excluded.card_identity_id, set_id = excluded.set_id,
        collector_number = excluded.collector_number, rarity = excluded.rarity,
        finishes = excluded.finishes, has_back = excluded.has_back,
        image_override = excluded.image_override, is_default = excluded.is_default,
        content_hash = excluded.content_hash, is_removed = false, seen_at = now()
      WHERE cp.content_hash IS DISTINCT FROM excluded.content_hash OR cp.is_removed
      RETURNING (xmax = 0) AS inserted`;
    stats.printings.inserted = cpRes.filter((r) => r.inserted).length;
    stats.printings.updated = cpRes.length - stats.printings.inserted;

    // ---- Post-pass: soft-delete rows gone upstream (never hard-delete) -----
    const remCi = await sql`
      UPDATE card_identities ci SET is_removed = true
      WHERE ci.game_id = ${GAME_ID.optcg} AND NOT ci.is_removed
        AND NOT EXISTS (SELECT 1 FROM stage_ci s WHERE s.external_key = ci.external_key)`;
    stats.post_pass.identities_removed = remCi.count;
    const remCp = await sql`
      UPDATE card_printings p SET is_removed = true
      WHERE p.game_id = ${GAME_ID.optcg} AND NOT p.is_removed
        AND NOT EXISTS (SELECT 1 FROM stage_cp s WHERE s.id = p.id)`;
    stats.post_pass.printings_removed = remCp.count;
    // No slug pass (leader hubs are an M4+ decision — assign-leader-slugs is
    // GAME_ID.mtg-pinned on purpose), no prices, no legality rows.

    const [{ size }] = await sql<{ size: string }[]>`
      SELECT pg_database_size(current_database())::text AS size`;
    stats.db_size_bytes = Number(size);
    stats.duration_ms = Date.now() - started;

    await sql`UPDATE ingest_runs
      SET status = 'succeeded', finished_at = now(), stats = ${sql.json(stats as unknown as postgres.JSONValue)}
      WHERE id = ${runId}`;
    console.log(JSON.stringify(stats, null, 2));
  } catch (err) {
    const message = err instanceof Error ? (err.stack ?? err.message) : String(err);
    console.error(message);
    if (runId !== undefined) {
      await sql`UPDATE ingest_runs
        SET status = 'failed', finished_at = now(), error = ${message.slice(0, 4000)}
        WHERE id = ${runId}`.catch(() => {});
    }
    process.exitCode = 1;
  } finally {
    await sql.end();
  }
}

main();
